### ISSUE TITLE
Visual CSS Can't be saved after resetting a color/background-color

### ISSUE THREAD

**Issue by RogerAntonio** [microweber/microweber#885] opened 2022-06-16 14:42 UTC
After resetting a element's custom configuration, the visual CSS can no longer be saved because it calls an error on any line with empty values.

E.G. Here it said can't save because of line 24.
![image](https://user-images.githubusercontent.com/5510591/174095539-74645713-fc43-42fb-98ee-bfa9143827d3.png)

Removing the entire line instead of only the value could fix this.

**Comment by peter-mw** [comment] 2022-06-22 16:53
Thanks for report, the issue is fixed now in version 1.2.18

**Closed** 2022-06-22 17:41 UTC
